import './globals.css'
import { Inter } from 'next/font/google'
import {SocketProvider} from './SocketContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SocketProvider>
      <body className="min-h-screen flex items-center justify-center bg-gradient-from-br from-[#DDEEED] via-[#DDEEED] to-[#FDF1E0]">{children}</body>
      </SocketProvider>
    </html>
  )
}
